# Config for continuous consolidation
bucketsToConsolidate: # The source buckets
  - bucket: 'support-infra-datadog-logs-rehydrate-archives' # Datadog Archives
    path:
      - datefmt: 'nginx/dt=20060102/hour=15'
  - bucket: 'support-infra-raw-logs-archives'
    path:
      - datefmt: '2006/01/02/15'
    force_env: support
  # Fix 2: Consolidate raw-log-archives from int stg prd
  - bucket: 'int-infra-raw-logs-archives'
    path:
      - datefmt: '2006/01/02/15'
    force_env: int
    proceed_without_matching_objects: true
  - bucket: 'stg-infra-raw-logs-archives'
    path:
      - datefmt: '2006/01/02/15'
    force_env: stg
  - bucket: 'prd-infra-raw-logs-archives'
    path:
      - datefmt: '2006/01/02/15'
    force_env: prd
bucketsConsolidated: # Where the consolidated output goes. Only one element is really supported as of now.
  - bucket: support-infra-log-consolidator-archives
    # - bucket: support-infra-logs-consolidated-archives # test bucket
    path:
      - datefmt: "log-archives/dt=20060102/hour=15"
bucketsCheckerResults: # Where to find checker results
  - bucket: 'support-infra-log-consolidator-checker-data'
    path:
      - datefmt: 'results-continuous/dt=20060102/hour=15'
continuousConsolidation: # Parameters for continuous consolidation, where the consolidator determines a single target date on its own
  maxAge: 528h # 30 days
  minAge: 70m
  step: 1h
